### PR TITLE
MNT: Re-rendered with conda-build 3.18.11 and conda-smithy 3.7.4

### PR DESCRIPTION
**Pull request by hufngvuowng**

### CODE REVIEW

**Comment by hufngvuowng** [comment]
Hi @mrakitin! Could you review this PR please? Thank you!

**Comment by mrakitin** [comment]
I ran the command to enable CI (see https://nsls-ii-forge.github.io/docs/creating_packages.html#enable-ci-on-azure-pipelines). It looks like this wasn't executed for this feedstock before. Is it true, @tienhungvuong?

**Comment by mrakitin** [comment]
I made my corrections and used the updated config as recommended in the docs (from the `event-model` feedstock). Feel free to self-merge if it's passing.

**Review by mrakitin — APPROVED** [review]

**Comment by hufngvuowng** [comment]
Hi @mrakitin! Yes, I don't think I have the azure tokens to enable the CI on this repo. Thanks for fixing that and merging this PR!

> I ran the command to enable CI (see https://nsls-ii-forge.github.io/docs/creating_packages.html#enable-ci-on-azure-pipelines). It looks like this wasn't executed for this feedstock before. Is it true, @tienhungvuong?

**Comment by mrakitin** [comment]
OK, thanks for the clarification. It's a one-time process per a new feedstock, and can be handled by DAMA.

**Pull request merged**
